### PR TITLE
Base the image off alpine

### PR DESCRIPTION
**Pull request by george-angel**

### CODE REVIEW

**Comment by ghost** [comment]
nice, 
does this result in us using the same version of mongodb as we do currently?

**Comment by george-angel** [comment]
I think its newer, @dgem said he would play around and see if nothing break.

**Comment by ghost** [comment]
okay, thanks.

Nice work on the continuing alpinification, btw.  Have you checked recently what's left using huge images as a base? possibly not not too much now (kafka?)

**Comment by george-angel** [comment]
Not much, you are probably right, might be a good idea to check.

It hasn't been an issue since we switch most of the apps, so we had the
bandwidth to pull the larger images.

**Comment by dgem** [comment]
Yer, I did say that!
I'll do you a deal... If you help me clean up my residual resources I'll
see if mongo on alpine works.
Cheers
Dan

sent by my droid

**Comment by george-angel** [comment]
I'm closing this for the lack of activity, but you should still have the branch if needed.

**Pull request closed without merging**
